components:
  schemas:
    Asset:
      type: object
      properties:
        spec:
          type: object
          properties:
            secretRef:
              description: Reference to a Secret resource holding credentials for this asset
              type: object
              properties:
                name:
                  description: Name of the Secret resource (must exist in the same namespace)
                  type: string
            tags:
              description: Tags associated with the asset
              items:
                type: string
              type: array
            schema:
              description: Schema information for rectangular data assets (can be partial)
              items:
                type: object
                properties:
                  name:
                    description: Column name
                    type: string
                  type:
                    description: Column type
                    type: string 
                  tags:
                    description: Tags associated with the column
                    items:
                      type: string
                    type: array
                required:
                - name
              type: array
            connection:
              description: Connection information
              type: object
          required:
          - connection
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Messages'
    Messages:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          type: integer
        text:
          type: string
