apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: qgw
spec: 
  gateways: 
    - dgw-gateway
  hosts: 
    - "*"
  http: 
    - 
      route:
        -
          destination:
            host: rest-read
            port:
              number: 5559

