apiVersion: katalog.m4d.ibm.com/v1alpha1
kind: Asset
metadata:
  name: data-csv
spec:
  secretRef: 
    name: data-csv-creds
  tags:
  - nokia
  schema:
  - name: id
    tags:
    - PII
  - name: Lname
    tags:
    - PII
  - name: Age
    tags:
    - sensitive
  connection:
    s3:
      endpoint: "http://minio:9000"
      bucket: demo
      path: data.csv
      format: csv

