apiVersion: v1
data:
  main: |
    package katalog.example

    import data.kubernetes.assets

    filters[output] {
        count(rule)==0
        output = {"name": "Allow by default", "action": "Allow"}
    }

    filters[output] {
        count(rule)>0
        output = rule[_]
    }

    test1 {
       roles = input.role[_]
       roles.name = "moose"
    }

    test {
       input.operation = "READ"
       roles = data.role[_]
       roles.name = input.role
    }

    blockList[output] {
       count(blocked) == 0
       output = {"name":"Allow all URLs", "action": "None"}
    }

    blockList[output] {
        count(blocked)>0
        output = blocked[_]
    }

    rule[{"name": "Full priviledges for boss", "action": "Allow"}] {
        input.request.operation == "READ"
        input.request.role == "boss"
    }

    rule[{"name": "Redact PII columns for workers", "action": "RedactColumn", "columns": columns}] {
        asset := assets[input.request.asset.namespace][input.request.asset.name]
        input.request.role == "worker"
        columns := [c | asset.spec.assetMetadata.componentsMetadata[i].tags[_] == "PII"; c = i]
    }

    rule[{"name": "Block sensitive columns for workers", "action": "BlockColumn", "columns": columns}] {
        asset := assets[input.request.asset.namespace][input.request.asset.name]
        input.request.role == "worker"
        columns := [c | asset.spec.assetMetadata.componentsMetadata[i].tags[_] == "sensitive"; c = i]
    }

    rule[{"name": "Block videos not created by owning organization", "action": "FilterPred", "unknowns":"organisation", "inputs":{"organization"}, "ppName": "videoPartialPolicy"}] {
        input.request.asset.name == "videos"
    }

    videoPartialPolicy {
        data.organisation[_].label == input.organization
    }

    blocked[{"name": "Block employee_related tagged URLs for workers", "action": "BlockURL"}] {
       input.request.role == "worker"
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       asset.spec.assetMetadata.tags[_] == "employee_related"
    }

    blocked[{"name": "Block control tagged URLs for except for workers", "action": "BlockURL"}] {
       input.request.role != "worker"
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       asset.spec.assetMetadata.tags[_] == "control"
    }

    blocked[{"name": "Requested assets does not exist", "action": "BlockURL"}] {
       not assets[input.request.asset.namespace][input.request.asset.name]
    }

    blocked[{"name": "Access for user suspended", "action": "BlockURL"}] {
       input.request.role = "suspended"
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    openpolicyagent.org/policy: rego
  name: policy
  namespace: katalog-system
