apiVersion: katalog.m4d.ibm.com/v1alpha1
kind: Asset
metadata:
  name: api.traffic-cams
spec:
  secretRef:
    name: admin
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
  assetMetadata:
    tags:
    - video
    componentsMetadata:
      sensors: 
        tags:
        - PII
      Age:
        tags:
        - PII
      Lname:
        tags:
        - sensitive
