apiVersion: katalog.m4d.ibm.com/v1alpha1
kind: Asset
metadata:
  name: status
spec:
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
  assetMetadata:
    tags:
    - unsafe
    componentsMetadata:
      Status:
        tags:
        - unsafe

