apiVersion: v1
data:
  main: |
    package katalog.example

    import data.kubernetes.assets

    filters[output] {
        count(rule)==0
        output = {"name": "No filtering by default!", "action": "Allow"}
    }

    filters[output] {
        count(rule)>0
        output = rule[_]
    }

    blockList[output] {
       count(blocked) == 0
       output = {"name":"Allow all URLs!", "action": "None"}
    }

    blockList[output] {
        count(blocked)>0
        output = blocked[_]
    }

    rule[{"name": "Full priviledges for admin", "action": "Allow"}] {
        input.request.role[_] == "Admin"
    }

    rule[{"name": "Block videos not created by owning organization if not Admin or Manager", "action": "FilterPred", "token" : "organization", "filterPredicate" : "WHERE organisation.label = '**T1**'", "replaceMe": "**T1**"}]  {
        input.request.asset.name == "videos"
        not contains(input.request.role, "Admin")
        not contains(input.request.role, "Manager")
    }

    rule[{"name": "Redact PII columns if not Manager or HR for personnel data", "action": "RedactColumn", "columns": columns}] {
        input.request.role[_] != "Manager"
        input.request.role[_] != "HR"
        lower_asset = lower(input.request.asset.name)
        asset := assets[input.request.asset.namespace][lower_asset]
        asset.spec.assetMetadata.tags[_] = "personnel"
        columns := [c | asset.spec.assetMetadata.componentsMetadata[i].tags[_] = "PII"; c = i]
    }

    rule[{"name": "Intrusion not cleared! Redact PII columns", "action": "RedactColumn", "columns": columns}] {
       statusasset := assets[input.request.asset.namespace]["status"]
       statusasset.spec.assetMetadata.tags[_] = "semisafe"
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       columns := [c | asset.spec.assetMetadata.componentsMetadata[i].tags[_] = "PII"; c = i]
    } 

    blocked[{"name": "No role in JWT - blocking", "action" : "BlockURL"}] {
        contains(input.request.role, "ERROR NO ROLE!")    
    }

    blocked[{"name": "UNSAFE - block all", "action": "BlockURL"}] {
       asset := assets[input.request.asset.namespace]["status"]
       asset.spec.assetMetadata.tags[_] == "unsafe"
    }

    blocked[{"name": "Block access to graphql if not Admin", "action": "BlockURL"}] {
       not contains(input.request.role, "Admin")
       asset := assets[input.request.asset.namespace][lower(input.request.asset.name)]
       asset.spec.assetMetadata.tags[_] = "graphql"
    }

    blocked[{"name": "Requested asset does not exist", "action": "BlockURL"}] {
       not assets[input.request.asset.namespace][lower(input.request.asset.name)]
    }

    blocked[{"name": "Access for user suspended", "action": "BlockURL"}] {
       input.request.role == "suspended"
    }

    blocked[{"name": "Block access to videos if not Admin, Manager or Editor", "action": "BlockURL"}] {
       not contains(input.request.role, "Admin")
       not contains(input.request.role, "Manager")
       not contains(input.request.role, "Editor")
       asset := assets[input.request.asset.namespace][lower(input.request.asset.name)]
       asset.spec.assetMetadata.tags[_] = "video"
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    openpolicyagent.org/policy: rego
  name: policy
  namespace: katalog-system

