apiVersion: v1
data:
  main: |
    package katalog.example

    import data.kubernetes.assets

    filters[output] {
        count(rule)==0
        output = {"name": "No filtering by default!", "action": "Allow"}
    }

    filters[output] {
        count(rule)>0
        output = rule[_]
    }

    blockList[output] {
       count(blocked) == 0
       output = {"name":"Allow all URLs!", "action": "None"}
    }

    blockList[output] {
        count(blocked)>0
        output = blocked[_]
    }

    rule[{"name": "Full priviledges for admin", "action": "Allow"}] {
        input.request.role[_] = "admin"
    }

    rule[{"name": "Redact PII columns if not Manager or HR for personnel data", "action": "RedactColumn", "columns": columns}] {
        input.request.role[_] != "Manager"
        input.request.role[_] != "HR"
        lower_asset = lower(input.request.asset.name)
        asset := assets[input.request.asset.namespace][lower_asset]
        asset.spec.assetMetadata.tags[_] = "personnel"
        columns := [c | asset.spec.assetMetadata.componentsMetadata[i].tags[_] = "PII"; c = i]
    }

    blocked[{"name": "UNSAFE - block all", "action": "BlockURL"}] {
       asset := assets[input.request.asset.namespace]["status"]
       output = {"name": asset.spec.assetMetadata.tags[_], "action": asset.spec.assetMetadata.tags[_] == "unsafe"}
    }

    blocked[{"name": "Block access to graphql if not admin", "action": "BlockURL"}] {
       input.request.role != "admin"
       asset := assets[input.request.asset.namespace][lower(input.request.asset.name)]
       asset.spec.assetMetadata.tags[_] = "graphql"
    }

    blocked[{"name": "Requested asset does not exist", "action": "BlockURL"}] {
       not assets[input.request.asset.namespace][lower(input.request.asset.name)]
    }

    blocked[{"name": "Access for user suspended", "action": "BlockURL"}] {
       input.request.role == "suspended"
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    openpolicyagent.org/policy: rego
  name: policy
  namespace: katalog-system

