##################################################################################################
# App service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }} 
  labels:
    app: {{ .Values.app.name }}  
    service: {{ .Values.app.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    name: https
    targetPort: {{ .Values.app.port }} 
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }} 
  labels:
    app: {{ .Values.app.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }} 
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.name }}  
        imagePullPolicy: Never
        ports:
        - name: https 
          containerPort: {{ .Values.app.port }}
        env:
        - name: VAULT_URI
          value: "http://kul-kms:5000" 
---
