# OPA and kube-mgmt
apiVersion: v1
kind: Service
metadata:
   name: opa
   labels:
     app: opa
     service: opa
spec:
  ports:
  - port: 8181  
    name: http
    targetPort: 8181
  type: NodePort
  selector:
    app: opa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: katalog-system
spec:
  selector:
    matchLabels:
      app: opa
  replicas: 1
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa
        args:
        - "run"
        - "--server"
        - "--log-level=info"
        - "--set=decision_logs.console=true"
        ports:
        - name: http
          containerPort: 8181
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.11
        args:
        - --require-policy-label
        - --policies=katalog-system
        - --replicate=katalog.m4d.ibm.com/v1alpha1/assets
