apiVersion: katalog.m4d.ibm.com/v1alpha1
kind: Asset
metadata:
  name: api.data.read-data
spec:
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
  assetMetadata:
    tags:
    - data
    componentsMetadata:
      sensors: 
        tags:
        - PII
      Age:
        tags:
        - PII
      Lname:
        tags:
        - sensitive
