apiVersion: katalog.m4d.ibm.com/v1alpha1
kind: Asset
metadata:
  name: api.control.testconn
spec:
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
  assetMetadata:
    tags:
    - control
    componentsMetadata:
      id: 
        tags:
        - PII
      age:
        tags:
        - sensitive
      Lname:
        tags:
        - sensitive
