apiVersion: v1
data:
  main: |
    package katalog.example

    import data.kubernetes.assets

    filters[output] {
        count(rule)==0
        output = {"name": "No filtering by default!", "action": "Allow"}
    }

    filters[output] {
        count(rule)>0
        output = rule[_]
    }

    blockList[output] {
       count(blocked) == 0
       output = {"name":"Allow all URLs!", "action": "None"}
    }

    blockList[output] {
        count(blocked)>0
        output = blocked[_]
    }

    rule[{"name": "Full priviledges for Manager", "action": "Allow"}] {
        input.request.operation == "READ"
        contains(input.request.role, "Manager")
    }

    rule[{"name": "Redact PII columns if not Manager or HR for personnel data", "action": "RedactColumn", "columns": columns}] {
        not contains(input.request.role, "Manager")
        not contains(input.request.role, "HR")
        asset := assets[input.request.asset.namespace][input.request.asset.name]
        asset.spec.assetMetadata.tags[_] == "personnel"
        columns := [c | asset.spec.assetMetadata.componentsMetadata[i].tags[_] == "PII"; c = i]
    }

    blocked[{"name": "Block data-related tagged URLs for HR", "action": "BlockURL"}] {
       contains(input.request.role, "HR")
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       asset.spec.assetMetadata.tags[_] == "data"
    }

    blocked[{"name": "Block order-related tagged URLs for all but Managers", "action": "BlockURL"}] {
       not contains(input.request.role, "Manager")
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       asset.spec.assetMetadata.tags[_] == "order"
    }

    blocked[{"name": "Block control tagged-URLs for HR", "action": "BlockURL"}] {
       input.request.role[_] == "HR"
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       asset.spec.assetMetadata.tags[_] == "control"
    }

    blocked[{"name": "Block personnel tagged-URLs if not Manager or HR", "action": "BlockURL"}] {
       not contains(input.request.role, "HR")
       not contains(input.request.role, "Manager")
       not contains(input.request.role, "Technician")
       asset := assets[input.request.asset.namespace][input.request.asset.name]
       asset.spec.assetMetadata.tags[_] == "personnel"
    }

    blocked[{"name": "Requested assets does not exist", "action": "BlockURL"}] {
       not assets[input.request.asset.namespace][input.request.asset.name]
    }

    blocked[{"name": "Access for user suspended", "action": "BlockURL"}] {
       input.request.role == "suspended"
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    openpolicyagent.org/policy: rego
  name: policy
  namespace: katalog-system

